blacklist: []
build_space: build
catkin_make_args: []
cmake_args:
- -O3
- -DCMAKE_CXX_CLANG_TIDY=clang-tidy-8
- -Wall
- -Wextra
- -Wpedantic
- -Werror
devel_layout: linked
devel_space: devel
extend_path: null
install: true
install_space: install
isolate_install: true
jobs_args: []
log_space: logs
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
